######################################################################
# Automatically generated by qmake (3.0) ??? ??? 1 21:27:06 2017
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += arrow.h dialog.h mygroup.h mysquare.h ui_dialog.h
FORMS += dialog.ui
SOURCES += arrow.cpp dialog.cpp main.cpp mygroup.cpp mysquare.cpp
