######################################################################
# Automatically generated by qmake (3.0) ??? ??? 9 21:20:49 2017
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += widgets
QT += svg

# Input
HEADERS += arrow.h dialog.h mygraphicsview.h mysquare.h mysvgitem.h
FORMS += dialog.ui
SOURCES += arrow.cpp \
           dialog.cpp \
           main.cpp \
           mygraphicsview.cpp \
           mysquare.cpp \
           mysvgitem.cpp
