######################################################################
# Automatically generated by qmake (3.0) ??? ??? 26 17:43:02 2017
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += arrow.h dialog.h mygroup.h mysquare.h ui_dialog.h
SOURCES += arrow.cpp dialog.cpp main.cpp mygroup.cpp mysquare.cpp
